#index:
#    path: /
#    controller: App\Controller\DefaultController::index

merci: 
  path: /merci
  controller: App\Controller\MonController::index


test_prem_route: 
  path: /test_prem_route/{nom}/{prenom}/{age}
  controller : App\Controller\TestController::index


test_regexp_route: 
  path: /test_regexp_route/{nom}/{prenom}/{age}
  defaults: 
    _controller: App\Controller\TestController::index
    nom: "Mouton--Besson"
    prenom: "Nicolas"
    age: 28
  requirements: 
    nom: "[[:alnum:]]+"
    prenom: "[-[:alnum:]]{2,10}"
    age: '\d{1,3}'


test_mon_show_route:
    path: /test_show_route{url}
    controller: App\Controller\TestController::showRoute
    defaults:
        _format: html
        url: /test_regexp_route/T/Marie/42
    requirements:
        url: '[0-9a-zA-Z/_]+'
    host: 127.0.0.1
    methods: GET

test_mon_include:
    path:  /test_include
    defaults:
      _controller: \App\Controller\TestIncludeController::index